### ISSUE TITLE
python setup.py sdist/bdist_wheel failing

### ISSUE THREAD

**Issue by fcollonval** [jupyter/jupyter-packaging#102]
With the latest version of jupyter-packaging, running `python setup.py sdist/bdist_wheel` will fail because the JS assets will be missing:

```
running sdist
running ensure_targets
Traceback (most recent call last):
  File "/home/fcollonval/projects/jupyterlab-gitlab/setup.py", line 105, in <module>
    setuptools.setup(**setup_args)
  File "/home/fcollonval/miniconda3/envs/jgit/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/fcollonval/miniconda3/envs/jgit/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/fcollonval/miniconda3/envs/jgit/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/fcollonval/miniconda3/envs/jgit/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/fcollonval/miniconda3/envs/jgit/lib/python3.9/site-packages/jupyter_packaging/setupbase.py", line 133, in run
    self.run_command('ensure_targets')
  File "/home/fcollonval/miniconda3/envs/jgit/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/fcollonval/miniconda3/envs/jgit/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/fcollonval/miniconda3/envs/jgit/lib/python3.9/site-packages/jupyter_packaging/setupbase.py", line 402, in run
    raise ValueError(('missing files: %s' % missing))
ValueError: missing files: ['/home/fcollonval/projects/jupyterlab-gitlab/jupyterlab_gitlab/labextension/package.json', '/home/fcollonval/projects/jupyterlab-gitlab/jupyterlab_gitlab/labextension/static/style.js']
```

**Comment by fcollonval** [comment]
Here is the failing job log: https://gitlab.com/beenje/jupyterlab-gitlab/-/jobs/1518166206
The repository is https://gitlab.com/beenje/jupyterlab-gitlab
