### ISSUE TITLE
Bug in ensure_python

### ISSUE THREAD

**Issue by frenzymadness** [jupyter/jupyter-packaging#93]
`ensure_python` does not work for Python 3.10:

```python
Python 3.10.0b2 (default, Jun  1 2021, 00:00:00) [GCC 11.1.1 20210428 (Red Hat 11.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jupyter_packaging.setupbase as pkg
>>> pkg.ensure_python(">=3.6")
<stdin>:1: DeprecatedWarning: ensure_python is deprecated as of 0.7 and will be removed in 1.0. Use `setuptools` `python_requires` instead
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lbalhar/.virtualenvs/tmp-5c2b09dccbe8317/lib/python3.10/site-packages/deprecation.py", line 260, in _inner
    return function(*args, **kwargs)
  File "/home/lbalhar/Software/jupyter-packaging/jupyter_packaging/setupbase.py", line 474, in ensure_python
    raise ValueError('Python version %s unsupported' % part)
ValueError: Python version 3.10 unsupported
```
I know it's deprecated but the 3.10 might be released sooner than the function disappears.

**Comment by frenzymadness** [comment]
I've tried to fix this but I'm not sure how to do that without any dirty hacks or usage of external libraries. Would it make sense, given the fact that the function is deprecated, to mark it also as not compatible with Python 3.10 and skip its test on that Python?

**Comment by blink1073** [comment]
> mark it also as not compatible with Python 3.10 and skip its test on that Python

Sounds good, would you like to make a PR for that as well?
